# Generated by Django 2.0.13 on 2019-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='first_added_text_or_name',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='story',
            name='last_added_text',
            field=models.TextField(max_length=140),
        ),
    ]
