# Generated by Django 2.0.13 on 2019-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20190603_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='finished',
            field=models.NullBooleanField(),
        ),
    ]
