# Generated by Django 2.0.13 on 2019-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20190603_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
