# Generated by Django 2.0.13 on 2019-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_story_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last',
            field=models.CharField(default='', max_length=40),
        ),
    ]
