# Generated by Django 2.0.13 on 2019-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_story_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='last',
            field=models.TextField(default='', max_length=40),
        ),
    ]
